// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('./Verifier');
var Proof = require('../../zokrates/code/square/proof');

// Test verification with correct proof
contract('TestSquareVerifier', accounts => {
    const owner = accounts[0];
  
    beforeEach(async() => {
        this.contract = await Verifier.new({from: owner});
    });
    it("should verify correct proof", async() => {
        let result = await this.contract.verifyTx.call(Proof.proof, Proof.inputs);
        assert.equal(result, true,"Correct proof not verified")
      });
    
// Test verification with incorrect proof
it("should not verify incorrect proof", async() => {
    let result = await this.contract.verifyTx.call(Proof.proof, [11, 15]);
    assert.equal(result, false, "Incorrect proof verified");
  });
});